CREATE TABLE IF NOT EXISTS DUB_COUNTRY(
COUNTRY_ID INT(5) NOT NULL AUTO_INCREMENT,
COUNTRY_NAME VARCHAR(50) NOT NULL UNIQUE
PRIMARY KEY(COUNTRY_ID)
)

CREATE TABLE IF NOT EXISTS DUB_STATE(
STATE_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
STATE_NAME VARCHAR(50) NOT NULL UNIQUE,
COUNTRY_ID INT(3) NOT NULL,
FOREIGN KEY FK_COUNTRY(COUNTRY_ID) REFERENCES DUB_COUNTRY(COUNTRY_ID)
)

CREATE TABLE IF NOT EXISTS DUB_CITY(
CITY_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
CITY_NAME VARCHAR(50) NOT NULL UNIQUE,
STATE_ID INT(2) NOT NULL,
FOREIGN KEY FK_STATE(STATE_ID) REFERENCES DUB_STATE(STATE_ID)
)

CREATE TABLE IF NOT EXISTS DUB_USER(
USERID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
PASSWORD VARCHAR(8) NOT NULL,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
COUNTRYCODE_PHONE_NUMBER INT(3) NULL,
STDCODE_PHONENUMBER INT(6) NULL,
PHONENUMBER INT(10) NOT NULL,
ADDRESS_1 VARCHAR(255) NOT NULL,
ADDRESS_2 VARCHAR(255) NULL,
PIN INT(8) NOT NULL,
CITY_ID INT(5) NOT NULL,
FOREIGN KEY FK_CITY(CITY_ID) REFERENCES DUB_CITY(CITY_ID),
STATE_ID INT(2) NOT NULL,
FOREIGN KEY FK_STATE(STATE_ID) REFERENCES DUB_STATE(STATE_ID),
COUNTRY_ID INT(3) NOT NULL,
FOREIGN KEY FK_COUNTRY(COUNTRY_ID) REFERENCES DUB_COUNTRY(COUNTRY_ID)
)

INSERT INTO DUB_COUNTRY(COUNTRY_ID,COUNTRY_NAME)VALUES(00001,'INDIA');
INSERT INTO DUB_STATE(STATE_ID,STATE_NAME,COUNTRY_ID)VALUES(0,'MADHYA PRADESH',00001);
INSERT INTO DUB_CITY(CITY_ID,CITY_NAME,STATE_ID)VALUES(0,'INDORE',1);
INSERT INTO DUB_CITY(CITY_ID,CITY_NAME,STATE_ID)VALUES(0,'MHOW',1);